#!/usr/bin/env python3
"""Resolve complete hash-locked release inputs for each declared build platform.

This command generates dependency inputs, not native-host or redistribution
approval evidence. Review the diff and verify each lock on its native builder.
The resolver executable is supplied explicitly and must match the pinned version.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "configs" / "release_dependency_locks.json"
LOCKS = ROOT / "requirements-locks"


def release_input_paths(root: Path, config: dict) -> list[Path]:
    return [
        root / "configs/release_dependency_locks.json",
        root / config["constraints"],
        *sorted((root / "requirements-locks/inputs").glob("*.in")),
    ]


def check_release_lf(root: Path, config: dict) -> list[str]:
    """Keep receipts bound to bytes that a normal Git checkout preserves."""
    errors: list[str] = []
    files = [*release_input_paths(root, config), *sorted((root / "requirements-locks").glob("*.txt"))]
    for path in files:
        if b"\r" in path.read_bytes():
            errors.append(
                f"{path.relative_to(root).as_posix()}: byte-hashed release inputs and locks require LF-only line endings; "
                "convert CRLF/lone CR to LF without changing pins, then refresh and review the resolution receipt"
            )
    required = {
        "*.json text eol=lf",
        "requirements-release.txt text eol=lf",
        "requirements-locks/*.txt text eol=lf",
        "requirements-locks/inputs/*.in text eol=lf",
    }
    attributes = root / ".gitattributes"
    actual = {" ".join(line.split()) for line in attributes.read_text(encoding="utf-8").splitlines()} if attributes.is_file() else set()
    for rule in sorted(required - actual):
        errors.append(f"root .gitattributes must preserve release receipt bytes with: {rule}")
    return errors


def compile_lock(uv: Path, config: dict, target: str, spec: dict, *, system_certs: bool) -> None:
    inputs = LOCKS / "inputs"
    output = LOCKS / f"{target}.txt"
    command = [str(uv)]
    if system_certs:
        command.append("--system-certs")
    command.extend([
        "pip", "compile", str(inputs / spec["input"]),
        "--quiet", "--no-header", "--no-annotate", "--generate-hashes",
        "--python-version", config["python_version"],
        "--python-platform", spec["platform"],
        "--default-index", config["resolver"]["index"],
        "--cache-dir", str(ROOT / ".tmp" / "uv-lock-cache"),
        "--constraint", str(ROOT / config["constraints"]),
        "--output-file", str(output),
    ])
    sources = spec.get("source_packages", [])
    if sources:
        command.extend(["--only-binary", ":all:", "--no-binary", ",".join(sources)])
    else:
        command.append("--no-build")
    subprocess.run(command, cwd=ROOT, check=True)
    contents = output.read_text(encoding="utf-8")
    if not re.search(r"(?m)^\w[\w.-]*==", contents) or "--hash=sha256:" not in contents:
        raise ValueError(f"resolver produced an empty or unhashed lock for {target}")
    header = (
        f"# Target: {target}; Python: {config['python_version']}; resolver: uv {config['resolver']['version']}\n"
        "# Generated by scripts/lock_release_dependencies.py; verify on the native builder.\n"
        "# This file is not runtime inventory or independent approval evidence.\n"
    )
    output.write_text(header + contents, encoding="utf-8", newline="\n")
    print(f"resolved {target}: {output.relative_to(ROOT).as_posix()}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--uv", type=Path, required=True)
    parser.add_argument("--target", action="append", help="target ID; omit to resolve all")
    parser.add_argument("--system-certs", action="store_true")
    args = parser.parse_args(argv)
    try:
        config = json.loads(CONFIG.read_text(encoding="utf-8"))
        line_errors = check_release_lf(ROOT, config)
        if line_errors:
            raise ValueError("; ".join(line_errors))
        uv = args.uv.resolve(strict=True)
        actual = subprocess.run([str(uv), "--version"], check=True, text=True, capture_output=True)
        version = re.match(r"^uv\s+(\S+)(?:\s|$)", actual.stdout.strip())
        if version is None or version.group(1) != config["resolver"]["version"]:
            raise ValueError(f"expected uv {config['resolver']['version']}, got {actual.stdout.strip()}")
        targets = args.target or list(config["targets"])
        for target in targets:
            if target not in config["targets"]:
                raise ValueError(f"unknown release-lock target: {target}")
        for target in targets:
            spec = config["targets"][target]
            compile_lock(uv, config, target, spec, system_certs=args.system_certs)
            if spec.get("bootstrap"):
                bootstrap = {
                    **spec,
                    "input": spec.get("bootstrap_input", "build-backends.in"),
                    "source_packages": [],
                }
                compile_lock(uv, config, f"{target}-bootstrap", bootstrap, system_certs=args.system_certs)
        line_errors = check_release_lf(ROOT, config)
        if line_errors:
            raise ValueError("; ".join(line_errors))
        files = release_input_paths(ROOT, config)
        receipt = {
            "schema_version": 1,
            "scope": config["evidence_scope"],
            "resolver": config["resolver"],
            "python_version": config["python_version"],
            "input_sha256": {path.relative_to(ROOT).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest() for path in files},
            "lock_sha256": {path.name: hashlib.sha256(path.read_bytes()).hexdigest() for path in sorted(LOCKS.glob("*.txt"))},
        }
        (LOCKS / "resolution.json").write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8", newline="\n")
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError) as exc:
        print(f"release lock resolution: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
